# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-15 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(default='', max_length=255, verbose_name='姓名')),
                ('password', models.CharField(default='', max_length=200, verbose_name='密码')),
                ('invite_code', models.CharField(default='', max_length=255, verbose_name='邀请码')),
                ('real_name', models.CharField(default='', max_length=255, verbose_name='真实姓名')),
                ('level', models.IntegerField(default=0, verbose_name='级别')),
                ('parent_id', models.IntegerField(default=0, verbose_name='上级id')),
                ('email', models.CharField(default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('id_card', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': '代理',
                'verbose_name_plural': '代理',
                'db_table': 'agent_user',
            },
        ),
    ]
