# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-15 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_user',
            name='address',
            field=models.CharField(default='', max_length=2000, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='agent_user',
            name='area',
            field=models.CharField(default='', max_length=2000, verbose_name='所属区域'),
        ),
        migrations.AddField(
            model_name='agent_user',
            name='cell',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent_user',
            name='money',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='agent_user',
            name='parent_pay_deduct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='agent_user',
            name='parent_share_deduct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='agent_user',
            name='pay_deduct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='agent_user',
            name='share_deduct',
            field=models.FloatField(default=0),
        ),
    ]
