#
# Autogenerated by Thrift Compiler (0.10.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
import sys
import adminIdl.ttypes

from thrift.transport import TTransport


class Rebate(object):
    """
    Attributes:
     - id
     - userId
     - refereeId
     - rebateNum
     - time
     - isHasReferee
    """

    thrift_spec = (
        None,  # 0
        (1, TType.I64, 'id', None, None, ),  # 1
        (2, TType.I64, 'userId', None, None, ),  # 2
        (3, TType.I32, 'refereeId', None, None, ),  # 3
        (4, TType.DOUBLE, 'rebateNum', None, None, ),  # 4
        (5, TType.I64, 'time', None, None, ),  # 5
        (6, TType.BOOL, 'isHasReferee', None, None, ),  # 6
    )

    def __init__(self, id=None, userId=None, refereeId=None, rebateNum=None, time=None, isHasReferee=None,):
        self.id = id
        self.userId = userId
        self.refereeId = refereeId
        self.rebateNum = rebateNum
        self.time = time
        self.isHasReferee = isHasReferee

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, (self.__class__, self.thrift_spec))
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I64:
                    self.id = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I64:
                    self.userId = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I32:
                    self.refereeId = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.DOUBLE:
                    self.rebateNum = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.I64:
                    self.time = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.BOOL:
                    self.isHasReferee = iprot.readBool()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('Rebate')
        if self.id is not None:
            oprot.writeFieldBegin('id', TType.I64, 1)
            oprot.writeI64(self.id)
            oprot.writeFieldEnd()
        if self.userId is not None:
            oprot.writeFieldBegin('userId', TType.I64, 2)
            oprot.writeI64(self.userId)
            oprot.writeFieldEnd()
        if self.refereeId is not None:
            oprot.writeFieldBegin('refereeId', TType.I32, 3)
            oprot.writeI32(self.refereeId)
            oprot.writeFieldEnd()
        if self.rebateNum is not None:
            oprot.writeFieldBegin('rebateNum', TType.DOUBLE, 4)
            oprot.writeDouble(self.rebateNum)
            oprot.writeFieldEnd()
        if self.time is not None:
            oprot.writeFieldBegin('time', TType.I64, 5)
            oprot.writeI64(self.time)
            oprot.writeFieldEnd()
        if self.isHasReferee is not None:
            oprot.writeFieldBegin('isHasReferee', TType.BOOL, 6)
            oprot.writeBool(self.isHasReferee)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
